source "https://rubygems.org"

gem "activerecord", "5.1.4"
gem "database_cleaner", "1.7.0"
gem "factory_bot", "4.10.0"
gem "pry"
gem "rake"
gem "require_all"
gem "rspec"
gem "sinatra"
gem "sinatra-activerecord", require: "sinatra/activerecord"
gem "sqlite3"
